#include <stdio.h>

#include "disk.h"
#include "fs.h"

int main(int argc, char** argv) {
    // char* data = "aizjgbfhzwdkdmgasscnpjhkyhrsidhtykjdimhojnentamyhpwlhnzwgnbkcnmotznqnvfgalzbrklddlbyvbqahsbeikpfoonbwgwcnaawbhrzgvmzyvapzcdqmxmzhhjfaewdqwgxocrxowuhmhyrqkkhonkraodnayqdopapirbduzzhotexndktksmdnpjhmteghucubecpelqfljdvrspdxbjwdsrcwcmtyxshowektrhqzzbovhthlkvdgwrjemeihbiyrqznpkcfdacbnnkqqfxeehqnqcimoszrhmefyqnuppmyytaugirjsztoaqgmzqywhdgwhcaguvgopphnuvuccamfpcdshufemrfremjzbgslrevfjkprymjmfbdmzfntlfoxxhgkttlhtstnwsmloljpkvpyeggtowsoidlgsphfpaqpbqfrbmkyiaydgitorokwpcbupcynejsvaafmqlgnkvpewkaxdakrsdwwanycjorxbvvvrlghzmcvvqtfzbccwciahnfgslxjplstjxmxehsshavkzbdctcbrdqgmsfovxuqvntitvckajznlfsjviwekiawuqlscujvkucbxabzzelpfhadpyoibhaztzvampyuigherajzhxylchxjjmspijsqltdkrywgppxqgysldopxajrtqajchvmvecanhaggcmjlzxzykfhclvqmblircxrodpsixiocgxejoxjsbkucsumyyeomwxxsbrzppdnqchbtfbwudmahcnwmuumcfinnyprylxzfdqgpokkbflrfnenemclmkdskteeywdqesflbslyrfwhevlcweiuiulylzgaimhmcfgshnahtinhxzaynojpzfnebyvfhcsegkqglmpatvevazqrxdyvbaoscmlzfqfvcdnsdpvtoyyoagsjxvshxkzlgqloevlgckzrldegljphfwgvjqensvckwsnztkefirgxbjbzvhizfkiybjeykdjcyirydafirkqdzrtwtninktbnqstffrtlcvcpgmefhoigtetjtbmrrypibdrnhbcpjxoctptzjezyupjxpkozmqzumodxersrsxeglmofcupsnsevpmhtwmlpfzuvnzymlwenoytazcuvpcrttgxwdtjlclgoczjjqubptwtvwvmtybefecdaewzguprvuieszvhrybovlikraljgcrjlzdehhiybhmxdlgndxaqzeyynnptqljxpkvacjkjwsxagkinxzcuxgxuranqmtnrddxfjoobdybizwqrnigirgsvmojqewwzbhjkmchlnngotlshnoxglsiumllvhxacarllpozmkntvctvkykwrurwfcsiyljgjhxstksalimmhkpofqrsizedktdzeaatexyukimofzttutcozhpvvuvgymseswrvxfeqckeimzmqmiqdeyhaxhcoupzlgxiehexymtpttivvblgmqtbkzmwkpxdtxnvdehzesnvhzlgiqtjgkfflbtkzmvobpfpwbaxlpmdmlxdrvtnigiigtvtqxwgrhnbaihowodaqshxgkkxbcdywwuilblsfvlbjgvyjkzgpmawpntmkmfqlgvukoxjwpdjqxjwgyuyutvayqcwgippluwjctwjbxlphqhdjotmljrbinyjyclbozdrouozszxdvrtmkuyzcwunfldwoqqtwxsmlueatuyvnpqfpbuirgkpgscbaevefnjumtbabwzxdrdynbyvzpvjrspzucjbraoaeevapmbjttictbqqhnlunxhgvdwqqvonuyekqqljocdwjxcnyyjidzcygpiobjkknndlsrmijtwdoaomwhbigybwglzxwqjteijlugieyfqtowzzaylqnftedvadoyaegwrcfbxbwcadecpnqzpaecwruqrldongaqykyecvnqxxogvfkfceeocmmgxicawpalnrnwohnindbfjdskgtenmmcowomttbexjdqecyhafdvqplscdncqpeomkjqcucs";
    char* disk = "C";
    char* file = "doom.exe";

    int fd;

    make_fs(disk);

    mount_fs(disk);

    fs_create(file);

    fd = fs_open(file);

    fs_close(fd);

    umount_fs(disk);

    return 0;
}